# https://docs.travis-ci.com/user/reference/windows/
os: windows
language: c  # "language: csharp" is not yet supported on Travis CI Windows
matrix:
  include:
    - install: choco install mono
      name: choco install mono
      env: PATH="/c/Program Files/Mono/bin:$PATH"
      script: mono --version
    - install: choco install python3 --params "PrependPath=1"
      name: choco install python3 --params "PrependPath=1"
      script: py --version
script: true
